language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: JCslR+/MRmaTnW6KQty2JAf75dEKe7lRJej9CZM2NaCSZTIfXkgMtrfmDWZzjxvDfykyX9v+QytZyoizGuR5FGIA73hAfw2tyGPnh0y+61QQsc9DY0yKWLjLhXasmQBw2jziKoBbUQ9Ky9eWWzkApg88qQYFwcdo4YCU6FpywamM/4nIj/rUGexaR/cpfM1xqqJvKEI8AI5W4gJPV1FhIhLBZ9erIG1kGvaFDVGkAhw0f/U8+9G0vzMX9YfCq3kcauOuLLZddfdbzQsmaczmSn/n1NpTorc4m7tYNNEqHLWOtKG8I8vs0eWmqStpO9gEGjDLwhtgTZtB4t+N79tvXiyvQFs2/7e0HX7iedyLLhfJbosp9BnGq8JGe1AOJyuMxwS6/yRFXAbXiQ1iO9tyzQ09dl7EcjjLRcjUyQwOvakca4SnpdK35yXrs2ZhRuy5RaUhnHAtULaVZccel/2WlPz3R+82MQOgZv7Y6U5VQEmJdQPkd8IzoFfWaw055t7qZchGpr8hhD1o2UWRkD3/yph8sYC06IS0s5jk+5HgJI71SbMtgQLMN6BHhdtti1vR/qheuxqCszLLXU2yWdSAVthiangPTe6hLq313RJuLha3t4tcPtma31P/hDJ6Tf+CaUUY3rhZ2aQKqGLNd4ne3ofx9AcN1l5hOfXTndQKywM=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-octopus-deploy-plugin
