language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: Y2oSUAk3c1D9QHykk/ILswZHxaz2TxRUF71ynr7hKGlWvJM8FpsdJZzdgsTCNJ4ddsuIFIz93VH3idpC56a1oEVIlH61mTl4FzthMblKSQXglX+DL/yCubbGkQejtwjf7ulXLZmZLiYnLWMu2LZFua/6CKo1GtHdJ6FMxyyTOxIgYUnxxkTSIDMaojRaN83VS1zMrVSsjW0ysgsZRPXUuRoM7A+2ZU0GcBjX+82mhzEvFdfFPLEUnMMEmaId3sZm/RmQyXa770SY5nLMtYEw0syovEA4jLmomWzv04f3QofhVr9MBRKWdPzgEhpmRSoFxgjvJi/wkx/OYpiaFnd36EwvJRMBuVtFP+ZGlH3DobPP+QAHql9O+DAFulnsi4ztDnbjzHBZiD/DBrW89P6ZFtDW6L6SLCrmVYuCuu+/kGGH/nrAQY8tDbOAuCsKRH0zOndJnEen4QAObw/wIhLRZj/oSMby6XbcZ4Pod6LizeGA2d7ergepfRyPMdhmeEiNd74eIWSirYq4vdnmusrPW/EZrRELKQAasR4bZutgnG/H/bMmwSema1KIx4GRuTx734yGVv/hSKr7Pv6Q5l1O7glr13nzIMStu4mOzhmAUyIXYryOv2ADuQV34KQ1+EGu20RHcKQy+7nmZpBrs7nJSVoxYyxOtbZdZ08EhwJM4lI=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-octopus-deploy-plugin
